### PR TITLE
Add PHP 8 on travis build matrix

### PR DESCRIPTION
**Pull request by DavidePastore**
We have to wait until PHP 8.0 is officially available on Travis.

Linked issues/PR: https://github.com/php-build/php-build/pull/651 and https://travis-ci.community/t/php-8-0-missing/10132/15.

### CODE REVIEW

**Comment by LvcioT** [comment]
Good evening.
Do you have any news?

**Comment by DavidePastore** [comment]
Hi @LvcioT. The problem here seems related to the Travis configuration I'm using. I have a second chance: move to GitHub Actions and remove Travis once for all.

**Comment by DavidePastore** [comment]
Superseded by #53.

**Comment by DavidePastore** [comment]
@LvcioT , new release published (0.8.0) 🎆

**Pull request closed without merging**
