### PR TITLE
Added Validator and InverseCalculator functionalities

### PR DESCRIPTION
**Pull request by antonioturdo**

### CODE REVIEW

**Comment by antonioturdo** [comment]
To make Travis CI build to pass I think the .travis.yml file should be modified about php 5.3 and hhvm, but I don't know how...

**Comment by DavidePastore** [comment]
@antonioturdo Thanks for this PR! First of all I'll try to fix the Travis build.

**Comment by DavidePastore** [comment]
Hi @antonioturdo, congratulations for your PR, it's a lot of work! 😄 Can you please improve test coverage? You can see its results [here](https://scrutinizer-ci.com/g/DavidePastore/codice-fiscale/inspections/c0258851-4ed7-4617-a8ba-1c2783fee4d4/code-structure/class/CodiceFiscale%5CValidator?expandCoverage=1). Furthermore, it would be awesome to also improve exception messages, so developers can better understand what is going on.

**Comment by antonioturdo** [comment]
Done.

**Comment by DavidePastore** [comment]
Thanks for your changes! 😄

**Comment by DavidePastore** [comment]
@antonioturdo All your work is included in the 0.3.0 release! 😎

**Pull request merged**
