### PR TITLE
Simplified namespaces

### PR DESCRIPTION
**Pull request by gadiener**
I think less is more :v:

### CODE REVIEW

**Comment by DavidePastore** [comment]
It could be ok for me, but I don't know if it's well to directly own the `CodiceFiscale` namespace. In this way it's simpler to use (or to import) but it can cause name collision if there are other package with the same namespace.
What do you think?

**Comment by gadiener** [comment]
I think it's a very rare case to find a package with the namespace "CodiceFiscale" and doing a little research I haven't found anyone.

**Comment by DavidePastore** [comment]
:+1: Can you also edit README.md to accordingly edit the documentation and remove the `DavidePastore` directories?

**Comment by gadiener** [comment]
:thumbsup: :wink:

**Comment by DavidePastore** [comment]
Thanks for the PR :+1:

**Comment by gadiener** [comment]
:grimacing:

**Pull request merged**
