### PR TITLE
Fix apostrophes in name and surname and changed array("elem") with ["elem"]

### PR DESCRIPTION
**Pull request by gadiener**

### CODE REVIEW

**Comment by DavidePastore** [comment]
Hi @gadiener, thanks for this PR. Is there any reason why we should remove support for PHP 5.3? I think that the actual implementation is not too focused on PHP 5.3 in mind.

**Comment by gadiener** [comment]
In php 5.3 is not possible to use the light version for the array declaration ($array = array() vs $array = []) . This makes the code more verbose but there isn't a best practices on this topic. It's just a matter of style and we are talking about an old php version of two years. I also fixed a problem with the apostrophe surnames. 

In any case, thanks for this library, it was very useful.:+1:

**Comment by DavidePastore** [comment]
@gadiener thanks for your words and your fix. What I'm not convinced of this PR is the elimination of support for PHP 5.3. Can you please link me some kind of best practice in this sense because I can't find any? For example I see that Twig supports PHP >= 5.2, though in the next major it will support only PHP >= 5.5. Let's discuss about this, I'm all ears.

**Comment by gadiener** [comment]
I found the usage statistics of the versions of php. 

> https://w3techs.com/technologies/details/pl-php/5/all

I think it is too early to drop support for PHP 5.3 for a library because it still has a large market share.
I'll change the PR leaving only the fix on apostrophes.

Thanks

**Comment by gadiener** [comment]
I'll send a new PR :wink::thumbsup:

**Pull request closed without merging**
